# Generated by Django 3.1.1 on 2020-09-24 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('NJ', 'Не ищу работу'), ('CO', 'Рассматриваю предложения'), ('LJ', 'Ищу работу')], max_length=30, verbose_name='Готовность к работе')),
                ('salary', models.IntegerField(blank=True, default=0, verbose_name='Ожидаемое вознаграждение')),
                ('grade', models.CharField(choices=[('IN', 'Стажер'), ('JR', 'Джуниор'), ('MD', 'Миддл'), ('SR', 'Синьор'), ('LD', 'Лид')], max_length=30, verbose_name='Квалификация')),
                ('education', models.TextField(blank=True, default='', null=True, verbose_name='Образование')),
                ('experience', models.TextField(blank=True, default='', null=True, verbose_name='Опыт работы')),
                ('portfolio', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Ссылка на портфолио')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='app_vacancies.specialty', verbose_name='Специализация')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
